let test_data = {
       "gravy_yum":{
          "name":"Gravy Yum",
          "tags":[
             "pvp",
             "farming",
             "enemies"
          ],
          "data":"",
          "color":"rgb(212,70,255)",
          "address":"keristero.xyz:8765",
          "description":"Water your crops then kick back for some nice warm gravy.",
          "last_alive_ts":1692582610991,
          "online_players":0,
          "map":{
             "farm":{
                "r":[
                   
                ],
                "name":"Gravy Farms",
                "l":{
                   "default":{
                      "id":"801"
                   }
                }
             },
             "tower":{
                "r":[
                   
                ],
                "name":"Gravy Yum",
                "l":[
                   
                ]
             },
             "default":{
                "r":{
                   "keristero.xyz:8766":{
                      "data":"681918",
                      "incoming_data":"keristerohp"
                   },
                   "99.15.113.82:8765":{
                      "data":"NA",
                      "incoming_data":"central3-gravy-yum-warp-xyz"
                   },
                   "142.93.58.233:8765":{
                      "data":"lev_beast_in_test"
                   },
                   "127.0.0.1:8765":{
                      "data":"NA",
                      "incoming_data":"lev_beast_in"
                   },
                   "d3str0y3d255.duckdns.org:8765":{
                      "data":"mm_gravy_yum_2",
                      "incoming_data":"REDACTED"
                   }
                },
                "name":"Gravy Yum",
                "l":{
                   "farm":{
                      "id":"54"
                   },
                   "gravy-pot":{
                      "id":"95"
                   }
                }
             },
             "gravy-pot":{
                "r":[
                   
                ],
                "name":"Gravy Pot",
                "l":{
                   "default":{
                      "id":"535"
                   }
                }
             }
          }
       },
       "net_city":{
          "description":"Hang out and build your own homepage",
          "tags":[
             "social"
          ],
          "address":"keristero.xyz:8766",
          "name":"Net City (beta)",
          "data":"",
          "color":"rgb(40,100,255)",
          "last_alive_ts":1692582553022,
          "online_players":0,
          "map":{
            "fake_keristero_hp":{
               "r":{
                  "keristero.xyz:8765":{
                     "data":"keristerohp",
                     "incoming_data":"681918"
                  }
               }
            },
             "base_homepage":{
                "r":[
                   
                ],
                "l":[
                   
                ]
             },
             "default":{
                "r":[
                   
                ],
                "name":"Net City",
                "l":[
                   
                ]
             }
          }
       },
       "IPCINFOBOARDV1":{
          "color":"rgb(0,128,128)",
          "data":"",
          "tags":[
             
          ],
          "name":"IPC Infoboard",
          "address":"85.215.186.121:8765",
          "description":"An old Infoboard infront of the IPC Tower, often used for NetBattle meetups",
          "last_alive_ts":1692583513243
       },
       "bn3":{
          "color":"rgb(0,0,255)",
          "description":"Recreation of the internet areas of BN3 with some QoL features, WIP",
          "name":"BN3",
          "tags":[
             "pvp"
          ],
          "data":"",
          "address":"159.223.165.219:3000",
          "last_alive_ts":1692584353921,
          "online_players":0,
          "map":{
             "AlphaLib1":{
                "name":"?",
                "l":[
                   
                ],
                "r":[
                   
                ]
             },
             "AlphaComp":{
                "name":"Alpha",
                "l":{
                   "default":{
                      "id":"25"
                   }
                },
                "r":[
                   
                ]
             },
             "ACDCSqr":{
                "name":"ACDC_Sqr",
                "l":{
                   "DexHP":{
                      "id":"6"
                   },
                   "ACDC3":{
                      "id":"10"
                   }
                },
                "r":[
                   
                ]
             },
             "default":{
                "name":"ACDC_1",
                "l":{
                   "DevRoom":{
                      "id":"2"
                   },
                   "ACDC3":{
                      "id":"34"
                   },
                   "DexHP":{
                      "id":"3"
                   },
                   "AlphaComp":{
                      "id":"2"
                   },
                   "ACDC2":{
                      "id":"20"
                   },
                   "MaylComp":{
                      "id":"8"
                   }
                },
                "r":{
                   "158.101.96.179:3066":{
                      "incoming_data":"Yoka4Life",
                      "data":"2C3NTR4L_AREA1abc"
                   }
                }
             },
             "Undernet3":{
                "name":"Undernet_3",
                "l":{
                   "UndernetSqr":{
                      "id":"28"
                   },
                   "Undernet2":{
                      "id":"41"
                   }
                },
                "r":[
                   
                ]
             },
             "BeachSqr":{
                "name":"Beach_Sqr",
                "l":{
                   "Beachside":{
                      "id":"8"
                   },
                   "TomakoHp":{
                      "id":"23"
                   }
                },
                "r":[
                   
                ]
             },
             "Beachside":{
                "name":"Beach_2",
                "l":{
                   "ShademanComp1":{
                      "id":"5"
                   },
                   "Hades":{
                      "id":"12"
                   },
                   "Beachside2":{
                      "id":"81"
                   },
                   "BeachSqr":{
                      "id":"3"
                   }
                },
                "r":[
                   
                ]
             },
             "Yoka1":{
                "name":"Yoka 1",
                "l":{
                   "Yoka2":{
                      "id":"95"
                   },
                   "TomakoHp":{
                      "id":"3"
                   }
                },
                "r":[
                   
                ]
             },
             "Undernet1":{
                "name":"Undernet_1",
                "l":{
                   "Hades":{
                      "id":"28"
                   },
                   "Undernet2":{
                      "id":"44"
                   }
                },
                "r":[
                   
                ]
             },
             "DexHP":{
                "name":"Dex_HP",
                "l":{
                   "default":{
                      "id":"15"
                   },
                   "ACDCSqr":{
                      "id":"7"
                   }
                },
                "r":[
                   
                ]
             },
             "ShademanComp1":{
                "name":"Elec_Twr1",
                "l":{
                   "Beachside":{
                      "id":"10"
                   },
                   "ShademanComp1":{
                      "id":"2"
                   }
                },
                "r":[
                   
                ]
             },
             "SecretArea2":{
                "name":"Secret Area 2",
                "l":{
                   "SecretArea1":{
                      "id":"3"
                   }
                },
                "r":[
                   
                ]
             },
             "Beachside2":{
                "name":"Beach_1",
                "l":{
                   "Beachside":{
                      "id":"65"
                   }
                },
                "r":[
                   
                ]
             },
             "Undernet5":{
                "name":"Undernet_5",
                "l":{
                   "UndernetSqr":{
                      "id":"36"
                   },
                   "Undernet6":{
                      "id":"3"
                   },
                   "Scilab1":{
                      "id":"41"
                   },
                   "Undernet4":{
                      "id":"16"
                   }
                },
                "r":[
                   
                ]
             },
             "Undernet2":{
                "name":"Undernet_2",
                "l":{
                   "Undernet2":{
                      "id":"67"
                   },
                   "Undernet1":{
                      "id":"49"
                   },
                   "Undernet4":{
                      "id":"17"
                   },
                   "Undernet3":{
                      "id":"41"
                   }
                },
                "r":[
                   
                ]
             },
             "YokaSqr":{
                "name":"Yoka_Sqr",
                "l":{
                   "Yoka2":{
                      "id":"33"
                   },
                   "MaylComp":{
                      "id":"9"
                   }
                },
                "r":[
                   
                ]
             },
             "Undernet4":{
                "name":"Undernet_4",
                "l":{
                   "Undernet5":{
                      "id":"5"
                   },
                   "Undernet2":{
                      "id":"40"
                   },
                   "Undernet4":{
                      "id":"44"
                   }
                },
                "r":[
                   
                ]
             },
             "Yoka2":{
                "name":"Yoka_2",
                "l":{
                   "YokaSqr":{
                      "id":"10"
                   },
                   "Yoka1":{
                      "id":"66"
                   }
                },
                "r":{
                   "150.136.139.228:8765":{
                      "incoming_data":"2",
                      "data":"1"
                   },
                   "173.25.45.82:8765":{
                      "data":"1"
                   }
                }
             },
             "YaiHp":{
                "name":"Yai_Hp",
                "l":{
                   "SciLabSqr":{
                      "id":"6"
                   },
                   "ACDC2":{
                      "id":"14"
                   }
                },
                "r":[
                   
                ]
             },
             "UndernetSqr":{
                "name":"Undernet_Sq",
                "l":{
                   "SecretArea1":{
                      "id":"2"
                   },
                   "Undernet3":{
                      "id":"43"
                   },
                   "Undernet5":{
                      "id":"8"
                   }
                },
                "r":[
                   
                ]
             },
             "Scilab2":{
                "name":"Scilab_2",
                "l":{
                   "SciLabSqr":{
                      "id":"3"
                   },
                   "Scilab1":{
                      "id":"36"
                   },
                   "GospelHQ":{
                      "id":"4"
                   }
                },
                "r":[
                   
                ]
             },
             "SecretArea1":{
                "name":"Secret Area 1",
                "l":{
                   "UndernetSqr":{
                      "id":"20"
                   },
                   "SecretArea2":{
                      "id":"1"
                   }
                },
                "r":[
                   
                ]
             },
             "MaylComp":{
                "name":"MaylHp",
                "l":{
                   "YokaSqr":{
                      "id":"12"
                   },
                   "default":{
                      "id":"16"
                   }
                },
                "r":[
                   
                ]
             },
             "DevRoom":{
                "name":"DevRoom",
                "l":{
                   "Undernet2":{
                      "id":"61"
                   },
                   "SecretArea1":{
                      "id":"2"
                   },
                   "Scilab2":{
                      "id":"14"
                   },
                   "default":{
                      "id":"124"
                   },
                   "Undernet4":{
                      "id":"39"
                   }
                },
                "r":[
                   
                ]
             },
             "ACDC3":{
                "name":"ACDC_3",
                "l":{
                   "ACDCSqr":{
                      "id":"4"
                   },
                   "default":{
                      "id":"32"
                   },
                   "ACDC2":{
                      "id":"21"
                   }
                },
                "r":[
                   
                ]
             },
             "ShademanComp2":{
                "name":"Elec_Twr2",
                "l":{
                   "ShademanComp1":{
                      "id":"6"
                   }
                },
                "r":[
                   
                ]
             },
             "Hades":{
                "name":"Hades",
                "l":{
                   "Beachside":{
                      "id":"30"
                   },
                   "Undernet1":{
                      "id":"50"
                   }
                },
                "r":[
                   
                ]
             },
             "SciLabSqr":{
                "name":"Scilab_Sqr",
                "l":{
                   "YaiHp":{
                      "id":"28"
                   },
                   "Scilab2":{
                      "id":"14"
                   }
                },
                "r":[
                   
                ]
             },
             "Undernet7":{
                "name":"Undernet_7",
                "l":{
                   "Undernet6":{
                      "id":"2"
                   }
                },
                "r":[
                   
                ]
             },
             "ACDC2":{
                "name":"ACDC_2",
                "l":{
                   "ACDC3":{
                      "id":"35"
                   },
                   "default":{
                      "id":"34"
                   },
                   "YaiHp":{
                      "id":"5"
                   }
                },
                "r":[
                   
                ]
             },
             "ACDC4Liberation":{
                "name":"ACDC 4",
                "l":[
                   
                ],
                "r":[
                   
                ]
             },
             "Undernet6":{
                "name":"Undernet_6",
                "l":{
                   "Undernet7":{
                      "id":"3"
                   },
                   "Undernet5":{
                      "id":"4"
                   }
                },
                "r":[
                   
                ]
             },
             "Scilab1":{
                "name":"Scilab_1",
                "l":{
                   "Undernet5":{
                      "id":"6"
                   },
                   "Scilab2":{
                      "id":"44"
                   }
                },
                "r":[
                   
                ]
             },
             "SecretArea3":{
                "name":"Secret Area 3",
                "l":[
                   
                ],
                "r":[
                   
                ]
             },
             "GospelHQ":{
                "name":"Gospel_HQ",
                "l":{
                   "SciLab2":{
                      "id":"11"
                   }
                },
                "r":[
                   
                ]
             },
             "TomakoHp":{
                "name":"Tomako_HP",
                "l":{
                   "Yoka1":{
                      "id":"45"
                   },
                   "BeachSqr":{
                      "id":"8"
                   }
                },
                "r":[
                   
                ]
             }
          }
       }
    }

export default test_data